config/routes.rb
Kuwest::Application.routes.draw do |map|

  devise_for "users", :path_names=>{:sign_in => 'login', :sign_out => 'logout', :sign_up => "new"}
  resources :users
  resources :wins
  resources :quest_definitions

  map.register  'register',     :controller=>"users", :action =>"new"
  map.profile   'profile',      :controller=>"users", :action =>"edit"
  map.top_users 'top-users',    :controller=>"users", :action =>"top"

  map.tos       'tos',          :controller=>"home",  :action =>"tos"
  map.about     'about',        :controller=>"home",  :action =>"about"
  map.root                      :controller=>"wins",  :action=>"index"

  resources :followings, :only => [:create, :destroy]
  map.after_twitter_login 'after_twitter_login', :controller => 'after_twitter_login', :action => 'login_to_devise'
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base

  has_many :wins
  has_many :quest_definitions
  has_many :quests
  has_many :comments

  has_many :follows, :class_name => 'Following', :foreign_key => "follower_id"
  has_many :followed_by, :class_name => 'Following', :foreign_key => "following_id"

  has_many :followers, :through => :followed_by
  has_many :followings, :through => :follows

  attr_accessible :username, :photo, :email, :password, :password_confirmation
  attr_accessible :first_name, :last_name, :public_name, :twitter_name, :url, :xp, :allow_email
  has_friendly_id :username
  validates_uniqueness_of :username
  validates_presence_of :username
  @@thumb, @@small, @@profile = "48x48#", "73x73#", "248z248"
  before_save :ensure_password_hack_for_twitter_accounts

  has_attached_file :photo,
          :storage        => :s3,
          :s3_credentials => "#{Rails.root}/config/s3.yml",
          :path           => ":attachment/user/:id/:style.:extension",
          :styles         =>  {
                              :thumb=> "48x48#",
                              :small  => "73x73#",
                              :profile => "248x248>" },
          :default_url    => "/images/:attachment/defaults/user_avatar_:style.gif"

  process_in_background :photo

  def ensure_password_hack_for_twitter_accounts
    if (self.password.nil? || self.password.length <1)
      self.password = self.password_confirmation = 'abc12345##'
    end
  end

  devise  :database_authenticatable,
          :registerable,
          :recoverable,
          :rememberable,
          :trackable,
          :validatable

  def to_s
    self.username
  end

  def gravatar_image(email)
    # get the email from URL-parameters or what have you and make lowercase
    email_address = email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    "http://www.gravatar.com/avatar/#{hash}?d=http://kuwest.com/images/photos/defaults/user_avatar_thumb.gif"
  end

  def the_photo(size)
    photo.exists? ? photo.url(size) : gravatar_image(email)
  end

  def following?(user)
    followings.include?(user)
  end

  def level
    return 0 if not xp
    User.xp_limits.each_index do |i|
      return i-1 if User.xp_limits[i] >= xp
    end
  end

  def level_progress
    return 0 if xp.nil?
    extra_xp = xp - User.xp_limits[level]
    extra_xp/(User.xp_limits[level+1]-User.xp_limits[level]).to_f
  end

  class << self
    def xp_limits
      [-1, 15, 20, 45, 80, 110, 150, 200, 275, 375, 500, 750, 1000, 1275, 1600, 1900, 2300]
    end

    def populate(user)
      user.password_confirmation = user.password = "abc123"
      user.email = "twitter_#{user.username}@twitter.com"
      user.save!
      user
    end

    # This will generate all the needed methods for devise
    def find_or_generate_by_username(username)
      user = find_or_create_by_username(username)
      populate(user) if (user.new_record?)
      user
    end

 # TODO:dunno why this doesn't work
 #  def find_or_create_by_username_with_populate(username)
 #    user = find_or_create_by_username_without_populate(username)
 #    user.password_confirmation = user.password = "abc123"
 #    user
 #  end

 #  alias_method_chain :find_or_create_by_username, :populate
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with => :user_not_found
  before_filter :authenticate_user!, :only => [:edit, :update]

  def new
    @user = User.new({:allow_email => true})
  end

  def top
    @users = User.find(:all, :conditions=>["xp > 0"], :order=>"xp DESC", :limit=>10)
  end

  def create
    @user = User.new(params[:user])
    @user.update_attributes(params[:username])

    if @user.save
      sign_in :user, @user
      add_stored_message
      flash[:notice] = "Your account has been created!"
      redirect_to user_path(@user)
    else
      render :action => :new
    end
  end

  def show
    #TODO: consider presenter
    @user = User.find(params[:id])
    @page = params[:page] || 1
    @wins = Win.paginate_by_user_id @user.id, {:page=> @page, :per_page=>25, :order=>"id DESC"}

    @title = "#{@user.username}'s profile [kuwest.com]"
    @totals = Win.totals_for(@user)
    @data = WinGraphData.new @user
    @can_update_status = !current_user.nil? && current_user.username == @user.username

    # TODO: this is not the same resource.
    respond_to do |format|
      format.html
      format.json { render :json => WinGraphData.new(@user) }
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update_attributes(params[:user])
      @user.save!
      flash[:notice] = "Profile updated."
      redirect_to user_path @user
    else
      render :action => :edit
    end
  end

  private

  def add_stored_message
      return unless cookies[:status]
      win_view_model = WinViewModel.new(
        :username=>@user.username,
        :body=>cookies[:status])
      win_view_model.to_win.save
  end

  def user_not_found
    @error = "Could not find User '#{params[:id]}'"
    render(:template => "shared/error404", :status => "404")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_badge_for(user)
    content_tag(:div, {:class => "profile_image" }) do
      image_tag user.the_photo(:profile), :class => "profile"
    end
  end
end

app/views/users/_form.haml
.field
  %p=f.label :username
  %p=f.text_field :username
.field
  %p=f.label :email
  %p=f.text_field :email
-if @user.new_record? && !params[:hide_password]
  .field
    %p=f.label :password
    %p=f.password_field :password
  .field
    %p=f.label :password_confirmation
    %p=f.password_field :password_confirmation
%a#expand_profile
  More profile fields....
.field
  %p=f.label :photo
  %p=f.file_field :photo, {:class=>"file"}
.profile
  .field
    %p=f.label :first_name
    %p=f.text_field :first_name
  .field
    %p=f.label :last_name
    %p=f.text_field :last_name
    /  .field
    /    %p=f.label :name_is_public
    /    %p=f.check_box :public_name
  .field
    %p=f.label :twitter
    %p=f.text_field :twitter_name
    / .field
    /   %p=f.label :location
    /   %p=f.text_field :location
    / .field
    /   %p=f.label :bio
    /   %p=f.text_field :bio
  .field
    %p=f.label :url
    %p=f.text_field :url
.field
  =f.check_box :allow_email
  =f.label :allow_email, "Allow us to contact you when new features are added to Kuwest!"

:javascript
  $(function() {
    #{"$('a#expand_profile').click();"  unless @user.twitter_name.blank?}
  });

app/views/users/edit.haml
%h2 Update Profile
.panel
  -form_for @user, :url => "/users/update", :html => {:multipart => true} do |f|
    =render :partial => "form", :locals => {:f=>f}
    %p=f.submit "Update", { :class=>"green" }

app/views/users/graph.haml
%h1#username=@user.username
-if @user.photo.exists?
  =image_tag @user.photo.url(:small)
#graph-options
  %button#line-graph line graph
  %button#column-graph column graph
  %button#stacked-column-graph stacked column graph
#graph-container{:style=>'width: 800px; height: 400px'}
%div{:style=>'clear:both'}

app/views/users/new.haml
.panel
  %h3 Register now to begin your quest(s)!
  -form_for @user,  :url => "/users/create", :html => {:multipart => true} do |f|
    =render :partial => "/users/form", :locals => {:f=>f}
    %p=f.submit "Sign up", {:class=>"green"}

app/views/users/show.haml
-content_for :sidebar do
  #user-information
    #level
      Level
      =@user.level
    %h1#username=@user.username
    #xp_bar{:progress=>@user.level_progress}
    = profile_badge_for @user
    -unless @user.location.nil?
      %h2=@user.location
    -unless @user.first_name.nil? || !@user.public_name
      %h2="#{@user.first_name} #{@user.last_name}"
    -if @user.twitter_name? && @user.twitter_name.length > 0
      %a{:href=>"http://twitter.com/#{@user.twitter_name}"}
        %h2="@#{@user.twitter_name}"
    -unless @user.url.nil?
      %a{:href=>@user.url}
        %h2=@user.url
    -unless @user.bio.nil?
      =@user.bio
    -unless @user.location.nil?
      %h2=@user.location
    -if user_signed_in? && current_user != @user
      %p
        -if current_user.following?(@user)
          = link_to 'Unfollow', following_path(:id => current_user.follows.find_by_following_id(@user.id)), :method => 'delete'
        -else
          = link_to 'Follow', followings_path(:following_id => @user.id), :method => 'post'

    -if @user.quest_definitions && @user.quest_definitions.length
      %h2 Quests Created:
      -@user.quest_definitions.each do |q|
        .info
          =link_to q.name, quest_definition_path(q)
    %h2 Totals
    #totals
      -@totals.each do |t|
        %p{:class=>'selected category', :category=>"#{t.verb}"}= "#{t.verb} #{t.total.to_f.pretty} #{t.noun}"
    .clear
    -unless @user.followers.empty?
      %h2 Followers

      %ul#followers
        -@user.followers.each do |follower|
          %li
            %img{:src => follower.photo.url(:thumb)}
    -unless @user.followings.empty?
      %h2 Following

      %ul#followings
        -@user.followings.each do |following|
          %li
            %img{:src => following.photo.url(:thumb)}
  =link_to "Create a new Quest", new_quest_definition_path
.panel
  =render :partial=>"/shared/new_status"
  %h1="#{@user.username}'s Quests"
  -@user.quests.each do |q|
    %h2
      =q.quest_definition.name
    -q.quest_objectives.each do |qo|
      =qo.to_s
      .remaining
        =qo.remaining_text
-if(@user.level > 2)
  #graph-container{:style=>'width: 680px; height: 270px'}
-else
  (Graph Unlocks at Level 3)
.info
#pages
  -@wins.reverse.each do |w|
    .status
      =render :partial => "shared/status", :locals => {:w=>w}
  = will_paginate @wins
= javascript_include_tag 'highcharts.src'
= javascript_include_tag 'kuwest_graph'

app/views/users/top.haml
.panel
  %h1
    Top Users
  .info
  %br
  %table#users
    %tr
      %th
      %th
        username
      %th
        level&nbsp;&nbsp;
      %th
        xp
      %th
        twitter
    -@users.each do |u|
      %tr
        %td.image_thumb
          .image
            =image_tag u.the_photo("thumb"), :class=>"thumb"
            &nbsp;
        %td
          %a{:href => users_path(u)}
            =u.username
        %td
          =u.level
        %td
          =u.xp || "0"
        %td
          %a{:href=>"http://twitter.com/#{u.twitter_name}"}
            =u.twitter_name
-content_for :sidebar do
  =render :partial => 'shared/homesidebar'