config/routes.rb
Kuwest::Application.routes.draw do |map|

  devise_for "users", :path_names=>{:sign_in => 'login', :sign_out => 'logout', :sign_up => "new"}
  resources :users
  resources :wins
  resources :quest_definitions

  map.register  'register',     :controller=>"users", :action =>"new"
  map.profile   'profile',      :controller=>"users", :action =>"edit"
  map.top_users 'top-users',    :controller=>"users", :action =>"top"

  map.tos       'tos',          :controller=>"home",  :action =>"tos"
  map.about     'about',        :controller=>"home",  :action =>"about"
  map.root                      :controller=>"wins",  :action=>"index"

  resources :followings, :only => [:create, :destroy]
  map.after_twitter_login 'after_twitter_login', :controller => 'after_twitter_login', :action => 'login_to_devise'
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/views/shared/_comment.haml
-comment ||= @comment
.comment
  =link_to comment.user.username, user_path(comment.user)
  =comment.body

app/views/shared/_devise_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('devise.sessions.link'), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('devise.registrations.link'), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to t('devise.passwords.link'), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('devise.confirmations.link'), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && controller_name != 'unlocks' %>
  <%= link_to t('devise.unlocks.link'), new_unlock_path(resource_name) %><br />
<% end -%>

app/views/shared/_feedback.erb
<script type="text/javascript" charset="utf-8">
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript" charset="utf-8">
  var feedback_widget_options = {};

  feedback_widget_options.display = "overlay";  
  feedback_widget_options.company = "kuwest";
  feedback_widget_options.placement = "right";
  feedback_widget_options.color = "  #171B34";
  feedback_widget_options.style = "idea";
  
  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
</script>

app/views/shared/_google_analytics.html.erb
<script type="text/javascript">var _gaq = _gaq || [];_gaq.push(['_setAccount', 'UA-16558432-1']);_gaq.push(['_trackPageview']);
  (function() {var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();</script>

app/views/shared/_homesidebar.haml
-if !user_signed_in?
  %a#signup.xp{:href=>"/users/new", :title=>"sign up"}
    %img{:src=>"/images/signup.png", :border=>0} 
  #signupxp.xp_value 10XP

.details
  %a.soon{:href=>"/about"}
    %h2 How Kuwest works
  .info
    Kuwest turns real life goals into an RPG, complete with XP, levels and achievements.  Quests are composed of small, quantifiable tasks that you share with your friends for both support and competition.
    %p
  %a
    %h2 How to
  .info
    %a.tip{:href=>"/tips/format_your_update.htm"}
      Format your Status Updates
    .paragraph
      %a.tip{:href=>"/tips/post_from_twitter.htm"}
        Post from Twitter
    .paragraph
      %a.tip{:href=>"/tips/level_up.htm"}
        Level Up
    .paragraph
      %a.tip{:href=>"/tips/contact_us.htm"}
        Contact Us
  %a
    %h2{:css=>"font-weight:bold"}Contest
  .info
    Players who reach at least level 5 by September 15 are elgible to win 1 of 10 laptop stickers from  
    %a{:href=>"http://www.etsy.com/shop/CraftyGalDecals", :target=>"new"}
      Crafty Gal Decals
  %a{:href=>"http://twitter.com/kuwest", :target=>"_new"}
    %h2 Twitter Feed
  .tweets.info

app/views/shared/_nav.haml
#nav
  -if user_signed_in?
    %a{:href=>"/wins/new"}
      new status
    |
    =link_to 'view profile', users_path(current_user)
    |
    %a{:href=>'/profile'}
      edit profile
    |
    %a{:href=>'/users/logout'}
      logout
  -else
    %a{:href=>"/users/login"}
      login
    |
    %a{:href=>"/users/new"}
      signup

app/views/shared/_new_status.haml
%form{:id=>"status_form", :method=>"POST", :action=>"/wins/create", :padding => "0px"}
  %input.xp{:id=>"win", :type=>"text", :name=>"body", :title=>"(ex: ran 3.2 miles, read 10 pages )"}
  #winxp.xp_value 3XP
  %input{:type=>"image", :id=>"submit_activity", :src=>"/images/green-go.png", :border=>"0", :style=>"position:relative; top:12px; left:5px;"}

app/views/shared/_status.haml
=w.verb
%span.amount
  =w.amount && w.amount.pretty
=w.noun
=days_ago(w.created_at.to_date)
=render :partial=>"shared/status_photo", :locals=>{:win=>w}
.comments
  -w.comments.each do |c|
    =render :partial=>"shared/comment", :locals=>{:comment=>c}
.action_wrapper	
  .actions  
    -if (!current_user.nil?)
      %a.comment.xp{:id => "cl#{w.id}", :href => ""} Comment
    -if (!current_user.nil? && current_user.id == w.user.id)
      %a.delete{:href=>"", :status=>w.id} Delete
      %a.edit{:href=>"/wins/edit/#{w.id}", :status=>w.id} Edit
    -if (!current_user.nil?)
      .xp_value{:id=>"cl#{w.id}xp"} 5 XP
      .comment_box{:class => "comment"} 
        %textarea{:class => "comment_description", :type => "text", :id => "comment_#{w.id}"}
        %button{:type => "submit", :class => "submit_comment" } 
          Add Comment

app/views/shared/_status_photo.haml
-win ||= @win
-if (win.photo.exists?)
  .status_image
    =image_tag win.photo.url(:small), {:class=>"status"}
-else
  -if (current_user && current_user.id == win.user.id)
    %a.upload{:href=>"", :id=>"upload#{win.id}", :status=>win.id} Upload an Image

app/views/shared/_status_tr.haml
- w ||= @win
%tr.status
  %td.profile_picture{:valign=>"top"}
    %a{:href => users_path(w.user), :class=>"username"}
      =image_tag w.user.the_photo("thumb"), :class=>"thumb"
  %td.detail
    %span.username
      %a{:href=> users_path(w.user), :class=>"username"}
        =w.user.username
    =render :partial => "shared/status", :locals => {:w=>@win || w}

app/views/shared/error404.haml
&nbsp;
%p
.error-div
  %h1 Whoa.  404.
%img{:src=>"/images/404-bw-small.png"}
%p
%h2 Sorry.  We can't find that here.
&nbsp;
%p
%a{:href=>"/"}
  %h2
    Back To The Home Page > 
&nbsp;