config/routes.rb
Kuwest::Application.routes.draw do |map|

  devise_for "users", :path_names=>{:sign_in => 'login', :sign_out => 'logout', :sign_up => "new"}
  resources :users
  resources :wins
  resources :quest_definitions

  map.register  'register',     :controller=>"users", :action =>"new"
  map.profile   'profile',      :controller=>"users", :action =>"edit"
  map.top_users 'top-users',    :controller=>"users", :action =>"top"

  map.tos       'tos',          :controller=>"home",  :action =>"tos"
  map.about     'about',        :controller=>"home",  :action =>"about"
  map.root                      :controller=>"wins",  :action=>"index"

  resources :followings, :only => [:create, :destroy]
  map.after_twitter_login 'after_twitter_login', :controller => 'after_twitter_login', :action => 'login_to_devise'
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/views/layouts/application.haml
!!! Strict
%html
  %head
    - @title ||= "Kuwest: tackle your real life quests."
    %title
      =@title
    = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'compiled/application.css'
    = stylesheet_link_tag 'slimbox/slimbox2'
    = stylesheet_link_tag 'bubbletip/bubbletip'
    = stylesheet_link_tag 'smoothness/jquery-ui-1.8.custom'
    %link{:rel=>"icon", :type=>"image/png", :href=>"/images/favicon.png"}
    /[if lt IE 8]
      = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
  %body
    .header.content
      #washout
        &nbsp;
      #logo
        %a{:href=>"/", :title=>"Kuwest.com"}
          %img{:src=>"/images/logo.png", :alt=>"Kuwest.com"}
      #topnav
        #socialmedia
          -unless user_signed_in?
            %a{:href=> '/login', :title=>"Login with Twitter"}
              %img{:src=>"http://a0.twimg.com/images/dev/buttons/sign-in-with-twitter-l.png", :border=>0}
        #login
          -unless user_signed_in?
            %form.login{:method=>"post", :action=>"/users/login"}
              %table
                %tr
                  %td
                    Already a member? Login:&nbsp;
                  %td
                    %input.hint{:type=>"text", :name=>"user[email]", :title=>"email"}
                  %td
                    %input.hint{:type=>"password", :name=>"user[password]", :title=>"password"}
                  %td
                    %input.noborder{:type=>"image", :src=>"/images/yellow-go.png", :value=>"Go!", :border=>"0"}
          -else
            %ul#links
              %li.first
                =link_to "new status", new_win_path
              %li
                =link_to 'profile', user_path(current_user)
              %li
                =link_to "edit profile", edit_profile_path
              %li
                %a{:href=>'/users/logout'}
                  logout

    .clearFix
    .bar
    #tip.chalk
      .close X
      .tip
    #messageDiv{:css=>"background-color:white"}
      #flashBubble{:style=>"display:none"}
        %pre{:class=>"tip"}
          ="{ deltaDirection: 'left' }"
      #flashMessage
        -if flash[:error] || @error  #HACK: clean this up
          .error=flash[:error] || @error
        -if flash[:notice] || @notice
          .notice=flash[:notice] || @notice
        -if flash[:alert] || @alert
          .alert=flash[:alert] || @alert
    #container.content
      #content
        = yield
      #sidebar
        = yield :sidebar
    #footer
      .content
        %a{:href=>"/tos"}
          Terms of Use
        %a.soon{:href=>"/terms"}
          Developers
        %a{:href=>"/about"}
          Business
        %a{:href=>"/about"}
          About
    = javascript_include_tag 'jquery'
    = javascript_include_tag 'jquery-ui-1.8'
    = javascript_include_tag 'mustache'
    = javascript_include_tag 'common'
    = javascript_include_tag 'jquery.upload'
    = javascript_include_tag 'slimbox2'
    = javascript_include_tag 'jquery.tweet'
    = javascript_include_tag 'bubble'
    = javascript_include_tag 'application'
    = javascript_include_tag  'http://use.typekit.com/wrf8sur.js'
    =render :partial => "shared/google_analytics"
    =render :partial => "shared/feedback"

app/views/layouts/bare.haml
!!!
%html
  %head
    %title awesome
  %body
    #content
      = yield
    #sidebar
      = yield :sidebar